plugins {
	id 'fabric-loom' version '1.13-SNAPSHOT'
	id 'maven-publish'
}

base {
    archivesName = project.archives_base_name
}

version = project.version+"+1.21"
group = project.maven_group

loom {
    accessWidenerPath = file('src/main/resources/fabrication.accesswidener')

    mods {
        "fabrication" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
	maven {
		url 'https://repo.sleeping.town/'
		content {
			includeGroup 'com.unascribed'
		}
	}
    maven {
        url 'https://maven.gegy.dev/releases/'
        content {
            includeGroup 'io.github.queerbric'
        }
    }
	maven {
		url 'https://maven.terraformersmc.com/releases/'
		content {
			includeGroup 'com.terraformersmc'
		}
	}
    mavenLocal()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "com.unascribed:ears-api:${project.ears_version}"
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}") {
        transitive = false
    }
	modImplementation("io.github.queerbric:pridelib:${project.pridelib_version}") {
		transitive = false
	}

    modImplementation include("com.unascribed:lib39-core:${project.lib39_version}")
	modImplementation include("com.unascribed:lib39-deferral:${project.lib39_version}")

	implementation 'com.google.code.gson:gson:2.13.1'
}

apply plugin: FabFeaturesPlugin
apply plugin: FabPagesPlugin

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
	dependsOn(fabGenFeatures)
}

sourceSets {
	dummy {
		compileClasspath += configurations.compileClasspath
	}
	main {
		compileClasspath += dummy.output
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    doFirst {
        StringBuilder bldr = new StringBuilder();
        File dir = file('build/classes/java/main');
        dir.eachFileRecurse(groovy.io.FileType.FILES, {
            if (it.name.endsWith('.class')) {
                bldr.append(it.getAbsolutePath().substring(dir.getAbsolutePath().length()+1))
                bldr.append('\n')
            }
        })
        file('build/tmp/classes.txt').text = bldr.toString();
    }

    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }

    from 'build/tmp/classes.txt'
}
