# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14

# Mod Properties
maven_group=com.unascribed
archives_base_name=fabrication
version=3.6.0

# Dependencies
fabric_version=0.115.6+1.21.1
ears_version=1.4.7
lib39_version=1.5.2+1.21.1
modmenu_version=11.0.3
pridelib_version=1.2.1+1.21
